# Note: We are now using projectVersion
projectVersion: 15.0 

name: Cairn
options:
  bundleIdPrefix: com.cairn
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    majorVersion: 5
targets:
  Cairn:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Cairn
    dependencies:
      - package: Alamofire
  CairnTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CairnTests
    dependencies:
      - target: Cairn
